version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  share-service:
    build:
      context: ./share-service
    ports:
      - '3001:3000'
    depends_on:
      - mongo
  flashcard-service:
    build:
      context: ./flashcard-service
    ports:
      - '3002:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
